apiVersion: v1
kind: ResourceQuota
metadata: # kpt-merge: example/base
  name: base
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: '|ResourceQuota|example|base'
spec:
  hard:
    requests.cpu: "40"
    requests.memory: 40G
